server:
  servlet:
    session:
      timeout: 86400
    contextPath: /
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain,application/stream+json
